In [26]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
path = "." # route to experiments folder

Notebook to read the datasets generated by all the experiments

Author: Oscar Fernández Vicente: ofvicente@gmail.com.

# 1- Agents data

Basic data generated by all the agents involved in simulations:

- DQN
- Random
- Persistent

In [19]:
names =["NUM_EXP", "iter", "last_state", "last_action", "reward", "accumreward", "lastkind", "splitted_rew", "marktovalue", "CASH","epsilon", "buyq", "sellq", "inventory", "spread"]

In [20]:
df = pd.read_csv(path + "/experiments/test/MORL/PARETO_0-1_alpha5_test/QL_1_REWARDS_PAPER_STATES123.bz2", names = names).dropna()

In [21]:
df

,NUM_EXP,iter,last_state,last_action,reward,accumreward,lastkind,splitted_rew,marktovalue,CASH,epsilon,buyq,sellq,inventory,spread
1,0,2,[[-7.38558201e-01 -7.76078773e-01 7.71281612e...,"[0.2, 0.2, 0.0, 0.0, 0.75]","[0.0, -0.0, 0.0]",0.000000,best,[],9.999575e+06,1.050000e+07,0,20,25,0.0,0.0
2,0,3,[[-0.38377617 -0.33876815 0.05978711 0.08006...,"[0.8, 0.6, 0.0, 0.0, 0]","[-5.0, -25.0, -25.0]",-25.000000,best,[],9.999555e+06,1.200128e+07,0,40,55,-5.0,1.0
3,0,4,[[-0.02899414 0.1860046 0.00776397 0.05954...,"[0.8, 1, 1.8, 2.0, 0.5]","[6.25, -90.0, -90.0]",-115.000000,best,[],9.999561e+06,1.175106e+07,0,0,0,-17.5,0.5
4,0,5,[[-0.7385582 -0.77607877 0.0164345 0.00823...,"[0.6, 0.6, 0.8, 0.8, 1]","[-8.75, -8.75, -8.75]",-123.750000,best,[],9.999552e+06,9.999552e+06,0,0,0,0.0,4.0
5,0,6,[[-0.7385582 -0.77607877 0.07712816 0.08006...,"[1, 0.8, 8.0, 7.2, 0]","[0.0, -0.0, 0.0]",-123.750000,best,[],9.999552e+06,9.999552e+06,0,0,0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107961,149,715,[[-7.38558201e-01 -7.76078773e-01 2.33197580e...,"[0.6, 0.6, 0.8, 0.8, 1]","[-22.5, -22.5, -22.5]",-172290.251086,best,[],1.008733e+07,1.008733e+07,0,0,0,0.0,1.0
107962,149,716,[[-0.7385582 -0.77607877 0.07712816 0.08006...,"[0.2, 0.2, 1.2, 1.2, 0.75]","[162.0, -0.0, 0.0]",-172290.251086,best,[],1.008857e+07,-3.451932e+06,0,135,0,0.0,2.0
107963,149,717,[[ 1.65622049 -0.77607877 0.54533642 0.08006...,"[1, 0.4, 4.0, 2.8, 0.75]","[3577.5, -675.0, -675.0]",-172965.251086,best,[],1.009215e+07,-3.451932e+06,0,0,0,135.0,1.5
107964,149,718,[[-0.7385582 -0.77607877 0.54533642 0.63417...,"[0.4, 0.6, 2.1, 2.4, 1]","[-202.5, -202.5, -202.5]",-173167.751086,best,[],1.009194e+07,1.009194e+07,0,0,0,0.0,0.5
107965,149,719,[[-0.7385582 -0.77607877 0.07712816 0.08006...,"[0.2, 0.2, 0.6, 0.6, 0.75]","[36.0, -0.0, 0.0]",-173167.751086,best,[],1.009168e+07,4.072269e+06,0,60,0,0.0,3.5

# 2- Market data

Additional market data generated by the interaction of the basic agents along the simulations. Gathered and saved by every MM agent. Some info can be shared with previous dataframes.

In [22]:
names =["buyq","sellq","inventory","lastinventory","midprice_var","spread","lastspread","lastVolume", "mid", "bid", "ask"]

In [23]:
df = pd.read_csv(path + "/experiments/test/MORL/PARETO_0-1_alpha5_test/QL_1_HISTORIC_PAPER_STATES123.bz2", names=names)

In [24]:
df.head()

,buyq,sellq,inventory,lastinventory,midprice_var,spread,lastspread,lastVolume,mid,bid,ask
0,0,0,0.0,0.0,100001.0,0.0,0.0,0,100000.0,0,0
1,20,25,-5.0,0.0,85.0,0.0,0.0,45,100085.0,0,0
2,40,55,-20.0,-5.0,1.0,1.0,0.0,95,100086.0,100085,100087
3,0,0,-17.5,-17.5,-0.5,0.5,1.0,0,100085.5,100085,100086
4,0,0,0.0,0.0,-5.5,4.0,0.5,0,100080.0,100076,100084